### PR TITLE
fix: fix repo to use new aegir

### PR DESCRIPTION
**Pull request by hugomrdias**
- fix: ts and lint errors
- chore: add docs to gitignore
- fix: fix setup for new aegir …
  - tweak tsconfig.js
  - add ts type check including test files
  - fix ci setup for new aegir
  - add new awesome aegir docs feature
    - you can publish to github pages with the flag --publish
- aegir now copies .d.ts to dist

/cc @vasco-santos 

needs:
https://github.com/ipfs/aegir/pull/730
- add back the cache after aegir release

### CODE REVIEW

**Review by vasco-santos — DISMISSED** [review]
LGTM! Thanks @hugomrdias 

@mpetrunic the CI job seems stalled. Can you restart it to check if everything is working?

**Comment by mpetrunic** [comment]
> LGTM! Thanks @hugomrdias
> 
> @mpetrunic the CI job seems stalled. Can you restart it to check if everything is working?

We ran out of free minutes on travis. We are actually paying and using github actions. I think it's just one time thing that we used our free minutes on travis since we had some fork running it's actions there.

Do we wait 4 more days to reset? 😄

**Comment by vasco-santos** [comment]
> Do we wait 4 more days to reset? 😄

We are also moving to github actions. So perhaps we can just change that here?

**Comment by mpetrunic** [comment]
> > Do we wait 4 more days to reset? smile
> 
> We are also moving to github actions. So perhaps we can just change that here?

not sure If I can push to this branch but I'll change ci right now

**Comment by hugomrdias** [comment]
if it helps
https://github.com/ipfs/aegir/wiki/Github-Actions-Setup

**Comment by mpetrunic** [comment]
> if it helps
> https://github.com/ipfs/aegir/wiki/Github-Actions-Setup

It helped :) I've added dependency caching to make thing a bit faster. Disabled bundle size checker since we still depend on bcrypto and node-forge which brings bundlesize to ~200kb. I think idea was to move crypto we need to libp2p-crypto but afaik it's not done yet

**Review by mpetrunic — APPROVED** [review]

**Comment by vasco-santos** [comment]
> I think idea was to move crypto we need to libp2p-crypto but afaik it's not done yet

Yes, that is still the plan, but we could not tackle it yet

**Comment by hugomrdias** [comment]
Some metrics with the new aegir 

Screenshot 2021-02-12 at 20 26 07

**Comment by mpetrunic** [comment]
You've added incremental flag to tsconfig? How do you deal with bugs it's causing (not deleting old files etc)?
How come you removed cache?

**Comment by hugomrdias** [comment]
The cache wasn't letting me pull the latest aegir. I will add it back once before merging.
Can you elaborate on the bugs from incremental?

**Comment by hugomrdias** [comment]
Actually theres no real need for incremental right now, gonna remove it.

**Comment by hugomrdias** [comment]
@mpetrunic can you point me to some issues created by --incremental ?

**Comment by mpetrunic** [comment]
> @mpetrunic can you point me to some issues created by --incremental ?

Most annoying it that it doesn't remove deleted source file from dist/build directory. That said, you are deleting whole dist directory on every build so it doesn't really matter but that also means that we are deleting tsconfig.tsbuildinfo so incremental flagisn't doing anything afaik.

**Comment by hugomrdias** [comment]
Screenshot 2021-02-18 at 16 49 44

docs preview

**Comment by mpetrunic** [comment]
@hugomrdias aegir is dropping node12 support? We need to remove it from CI here as well?

**Comment by hugomrdias** [comment]
> @hugomrdias aegir is dropping node12 support? We need to remove it from CI here as well?

aegir still works in node12 because the github-action needs it but everything else yes https://github.com/ipfs/community/blob/master/CONTRIBUTING_JS.md#supported-versions

> The IPFS JavaScript projects work with the Current and Active LTS versions of Node.js and respective npm version that gets installed with Node.js. Please consult nodejs.org for LTS timeline.

**Comment by hugomrdias** [comment]
@mpetrunic its finally ready

**Review by mpetrunic — APPROVED** [review]
awesome tnx @hugomrdias

**Pull request merged**
